In [1]:
import torch
import numpy as np

In [2]:
#  Training data
inputs = np.array([[73,67,43,],
                  [91,88,64],
                  [102,43,37],
                  [69,96,70]], dtype = 'float32')

In [3]:
#  targets (apples, oranages)
targets = np.array([[56,70],
                 [81,101],
                  [119,133],
                  [103,119]
                 ], dtype = 'float32')

In [4]:
#   converte to torch tesors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

#### Linear Regression model from scratch

In [5]:
#   weigths and biases
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

w,b

(tensor([[ 1.3361, -1.0135, -0.8507],
         [ 0.7384, -1.1702,  0.6009]], requires_grad=True),
 tensor([ 1.2464, -0.1750], requires_grad=True))

In [6]:
def model(x):
    return x@w.t() + b

In [7]:
preds = model(inputs)

### Using Pytorch builtins

In [8]:
import torch.nn as nn
from torch.utils.data import TensorDataset  # Allows access to rows from inpouts and targets as tuples and provides standard API

In [9]:
#  define the dataset
train_ds = TensorDataset(inputs, targets)

In [10]:
train_ds[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [11]:
from torch.utils.data import DataLoader
# The dataloader is used in for-in loop.

In [12]:
# define data loaderDa
batch_size = 3
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [13]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[119., 133.],
        [103., 119.],
        [ 56.,  70.]])


In each iteration dataloader returns one batch of data, with the guven batchsize. If shuffle is set to True, it shuffle s the training data before creating batches. shuffling helps ransomize the inpout to the optimization algoritm. which can kead to faster reduction in the loss

## nn.Linear

In [14]:
# define the model

model = nn.Linear(3,2)
model.weight, model.bias

(Parameter containing:
 tensor([[-0.1258, -0.2920, -0.1228],
         [-0.5275, -0.1612,  0.1222]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3380, -0.1240], requires_grad=True))

In [15]:
#  parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.1258, -0.2920, -0.1228],
         [-0.5275, -0.1612,  0.1222]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3380, -0.1240], requires_grad=True)]

In [16]:
#  generate predictions 
preds= model(inputs)

## loss function

In [17]:
import torch.nn.functional as F

In [18]:
# The nn.functional package onatins useful loss functions and several other utils

In [19]:
#  Define the loss
loss_fn = F.mse_loss

In [20]:
loss = loss_fn(model(inputs), targets)
loss

tensor(20907.4883, grad_fn=<MseLossBackward>)

## optimizer

 Instead of manually manupulating the model's weight and biases usin gradients. we can use the optimizer optim.SGD,
    

In [21]:
opt = torch.optim.SGD(model.parameters(), lr = 0.001)

Note that mode.parameters() is passed as an arguement to the opti.SGD, so that the optimizer knows which matruces should be modifired during the update step 

## Train the model

In [34]:
x = inputs
y = targets
x.shape, targets.shape, w.shape,b.shape

(torch.Size([4, 3]), torch.Size([4, 2]), torch.Size([2, 3]), torch.Size([2]))

In [37]:
 def model(x):
        return x@w.t() +b

In [40]:
#  genrtrate predictions 

preds = model(x)
preds, targets

(tensor([[ -5.7034,   1.1620],
         [-20.8018,   2.4975],
         [ 62.4711,  47.0543],
         [-63.4078, -19.5030]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [103., 119.]]))