In [17]:
import torch
import torch.nn as nn
import numpy as np

In [71]:
x = np.random.randn(20,2).astype('float32')
x.shape

(20, 2)

In [72]:
y = np.arange(20, dtype = np.float32)
y = y[...,np.newaxis]
y.shape

(20, 1)

In [73]:
inputs  = torch.from_numpy(x)
targets = torch.from_numpy(y)

In [75]:
inputs.shape,targets.shape

(torch.Size([20, 2]), torch.Size([20, 1]))

In [76]:
from torch.utils.data import TensorDataset

In [77]:
train_ds = TensorDataset(inputs, targets)

train_ds[:3]

(tensor([[-1.2943, -1.0099],
         [ 2.3307,  1.7659],
         [-2.3683,  0.4250]]),
 tensor([[0.],
         [1.],
         [2.]]))

In [78]:
from torch.utils.data import DataLoader # split data into batches

In [79]:
batch_Size = 5
train_dl =  DataLoader(train_ds, batch_Size, shuffle = True)

In [80]:
 for xb, yb in train_dl:
        print(xb, yb)
        break

tensor([[ 0.0114, -0.8892],
        [ 0.8028, -0.5224],
        [-1.7262, -0.7865],
        [-1.2943, -1.0099],
        [-0.1666, -1.0231]]) tensor([[15.],
        [16.],
        [19.],
        [ 0.],
        [ 8.]])


In [81]:
#  define the model

model = nn.Linear(2,1)
print(model.weight, model.bias)

Parameter containing:
tensor([[ 0.1528, -0.4795]], requires_grad=True) Parameter containing:
tensor([-0.2623], requires_grad=True)


In [82]:
#  parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1528, -0.4795]], requires_grad=True),
 Parameter containing:
 tensor([-0.2623], requires_grad=True)]

In [83]:
preds = model(inputs)
preds

tensor([[ 0.0242],
        [-0.7528],
        [-0.8280],
        [-0.0848],
        [-0.5763],
        [-0.2125],
        [-0.1861],
        [-0.1209],
        [ 0.2029],
        [-0.1319],
        [-0.3470],
        [ 0.1367],
        [-0.3188],
        [-0.2812],
        [-0.3143],
        [ 0.1659],
        [ 0.1109],
        [-0.7178],
        [ 0.6827],
        [-0.1489]], grad_fn=<AddmmBackward>)

In [84]:
#  loss function
import torch.nn.functional as F


In [85]:
# define the loss function
loss_fn = F.mse_loss

In [89]:
#  compute the loss for the current preds

loss = loss_fn(model(inputs), targets)
loss

tensor(125.6491, grad_fn=<MseLossBackward>)

In [91]:
# optimizer

opt = torch.optim.SGD(model.parameters(), lr = 0.001)

## Train The Model

In [96]:
#  utility functions to train the model

def fit(num_epochs, model, loss_f, opt):
    # train for a given nuber of epochs
    for epoch in range(num_epochs):

        for xb, yb in  train_dl:
            # 1. Generate preds
            pred = model(xb)

            # 2. Calculate the loss
            loss = loss_fn(pred, yb)
            # compute the grads
            loss.backward()
            # 4. Update the parameters using gradients
            opt.step()
            # 5. Reset the gradients to zero
            opt.zero_grad()
        # print the progress
        if (epoch+1)%10 == 0:
            print('Epoch [{}/{}], loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))
        
        

In [97]:
fit(100, model, loss_fn, opt)

Epoch [10/100], loss: 150.8906
Epoch [20/100], loss: 90.8361
Epoch [30/100], loss: 123.2227
Epoch [40/100], loss: 76.3497
Epoch [50/100], loss: 86.3798
Epoch [60/100], loss: 80.1748
Epoch [70/100], loss: 59.6872
Epoch [80/100], loss: 75.2912
Epoch [90/100], loss: 45.1784
Epoch [100/100], loss: 5.1798


In [99]:
preds = model(inputs)

preds

tensor([[7.4818],
        [1.6059],
        [4.4021],
        [3.2701],
        [3.0804],
        [5.4387],
        [6.8766],
        [5.9566],
        [7.5262],
        [5.4534],
        [5.8503],
        [7.6197],
        [5.8010],
        [5.2708],
        [4.9050],
        [7.2429],
        [6.4708],
        [2.9844],
        [9.2343],
        [6.9986]], grad_fn=<AddmmBackward>)

In [100]:
targets

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.]])